### ISSUE TITLE
rstudio-server "error 61" after reboot; rebuilding from source works

### ISSUE THREAD

**Issue by lazyatom** [brewsci/homebrew-base#20]
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new or https://github.com/Linuxbrew/brew/issues/new.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?

I'm adding this more as a record in case anyone else hits it, but hopefully it might also be useful to maintainers.

After a recent reboot, rstudio-server stopped working. When visiting it in a browser, after logging in the error message "Unable to connect to service" appears. In the system logs (`/var/log/system.log`) output of the following form appears:

```
Oct 22 13:49:04 iMac rserver[1764]: ERROR system error 61 (Connection refused) [request-uri=/rpc/client_init]; OCCURRED AT: void rstudio::core::http::LocalStreamAsyncClient::handleConnect(const boost::system::error_code &) /tmp/rstudio-server-20190516-24750-15buw5s/rstudio-1.2.1335/src/cpp/core/include/core/http/LocalStreamAsyncClient.hpp:119; LOGGED FROM: void rstudio::server::session_proxy::(anonymous namespace)::logIfNotConnectionTerminated(const rstudio::core::Error &, const http::Request &) /tmp/rstudio-server-20190516-24750-15buw5s/rstudio-1.2.1335/src/cpp/server/ServerSessionProxy.cpp:373
```

`brew doctor` shows no issues, and reinstalling `rstudio-server` from bottle also failed to resolve it. Running `sudo rstudio-server verify-installation` exits with `0`, and `sudo rstudio-server test-config` also exits with `0`. Rebooting multiple times had no effect, and turning off anti-virus also didn't resolve the issue.

The computer is running system version `macOS 10.14.5 (18F132)`.

What ultimately resolved it was rebuilding this formula from source:

```
brew install boost-rstudio-server
brew cask install homebrew/cask-versions/adoptopenjdk8
brew install rstudio-server -s
```

I wonder if anyone else has hit this recently? I also noticed that the version of Xcode being used to build the bottle is `9.0`, whereas the current version of Xcode is at least `11`; might that be related?

Anyway, I hope this is useful to someone.

**Comment by randy3k** [comment]
Hi @lazyatom I have updated the formula to v.1.2.5001 in https://github.com/brewsci/homebrew-base/pull/21

Hopefully rebottling a new binary will fix your issue.
